server:
  port: 8080
  servlet:
    context-path: /kasa
  tomcat:
    uri-encoding: utf-8
  # 关闭springboot 默认异常处理
  error:
    whitelabel:
      enabled: false
spring:
  #出现错误时, 直接抛出异常(便于异常统一处理，否则捕获不到404)
  mvc:
    throw-exception-if-no-handler-found: true
    #不要为我们工程中的资源文件建立映射
  resources:
    add-mappings: false
  freemarker:
    cache: false
    request-context-attribute: request
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      dingpush:  #数据源
        url: jdbc:mysql://47.110.43.11:3306/kasa?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: ALY2019@@
      first:  #数据源1
        url: jdbc:mysql://47.110.43.11:3306/kasa?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: ALY2019@@
      second:  #数据源2 只读库
        url: jdbc:mysql://  /kasa?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: ALY2019@@
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      connectionInitSqls: SET NAMES utf8mb4
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
          #login-username: admin
          #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  # redis config
  redis:
          #Redis数据库索引（默认为0）
          database: 0
          host: 47.110.43.11
          password: ALY2019@@
          port: 6379
          jedis:
              pool:
                  #连接池最大连接数（默认为8，负数表示无限）
                  max-active: 1000
                  #连接池中的最大空闲连接（默认为8，负数表示无限）
                  max-idle: 10
                  #连接池最大阻塞等待时间（默认为-1，单位为毫秒，负数表示无限）
                  max-wait: -1
                  # 连接池中的最小空闲连接（默认为0，该值只有为正数才有作用）
                  min-idle: 5
          open: false
          #连接超时时间（毫秒）
          timeout: 20000
          cluster:
            max-redirects:

# 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.pine.kasa.model.entity  # 注意：对应实体类的路径

# 通用mapper
mapper:
  mappers: tk.mybatis.mapper.common.BaseMapper
  not-empty: false
  identity: MYSQL


#pagehelper
pagehelper:
  helperDialect: mysql
  # true 没有数据的页数永远查最后一页
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

---

picture:
   url: https://media.forwe.store/community/image/portal_default.jpg

environment:
 sign: test


yuming:
  url: https://pretest.forwe.store

# 分布式配置
distributed:
  config:
    file: /Users/lius/Documents/worker.cfg

web-config: #自定义的属性和值
  root-upload-path: community-test
  parent-folder: /community
  domain-name: https://pretest.forwe.store
  suite-id: 4392002
  appid: 10469
  webhook: 
  working-group-webhook: 
  listprop1:
    - name: abc
      value: abcValue
    - name: efg
      value: efgValue
  listprop2:
    - config2Value1
    - config2Vavlue2
  mapprops:
    key1: value1
    key2: value2
